### ISSUE TITLE
Op Support: aten.fill.Tensor

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/torch_migraphx#116]
Add aten converter.
Affected models:
Torchbench: pyhpc_turbulent_kinetic_energy

**Comment by CharlieL7** [comment]
MIGraphX does not yet have a GPU fill operator. Would need to implement it to complete this issue.

**Comment by shivadbhavsar** [comment]
We might be able to partially resolve this in cases where the fill input is a constant. There are some passes that do this for `torch.zeros, torch.full, torch.arange` etc

**Comment by causten** [comment]
This seems similar to #146
