### ISSUE TITLE
Op Support: aten.logical_not.default

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/torch_migraphx#117]
Add aten converter.
Affected models:
Torchbench: pyhpc_turbulent_kinetic_energy

**Comment by bpickrel** [comment]
Will this require a new `migraphx` NOT operator?  Boolean NOT is a primitive operation and I don't think it can be created from the logical ops we have:  AND, OR, and XOR.

Needs to have an acc converter created alongside the aten converter.

**Comment by bpickrel** [comment]
No new op required; found it hiding under the name `unary_not`.

**Comment by bpickrel** [comment]
See [PR #167](add converters for logical_not, for both aten and acc. Includes tests #167)
