### ISSUE TITLE
TIMM COMPUTE_BROADCASTLEN Error

### ISSUE THREAD

**Issue by shivadbhavsar** [ROCm/torch_migraphx#37]
Errors of the form:
`RuntimeError: /workspace/AMDMIGraphX/src/common.cpp:48: operator(): COMPUTE_BROADCASTLEN: shape {192} and {192, 28, 28} mismatch!`

Affected models: pit_b_224, visformer_small

**Comment by shivadbhavsar** [comment]
Created more focused issue with low-overhead repro: https://github.com/ROCm/AMDMIGraphX/issues/2722

**Comment by causten** [comment]
Fixed via #3002
