### ISSUE TITLE
torch-migraphx test fail for model pit_b_224

### ISSUE THREAD

**Issue by bpickrel** [ROCm/torch_migraphx#81]
The following torch-migraphx test command leads to an exception in Migraphx. Troubleshoot and fix.

`python ./benchmarks/dynamo/timm_models.py --inference --float16 -dcuda --performance --backend migraphx -k pit_b_224`

An exception is thrown during the `simplify_algebra` pass, trying to broadcast between two shapes that aren't broadcastable.

**Comment by causten** [comment]
Shiv says this is fixed, he will do a quick check

**Comment by shivadbhavsar** [comment]
Model runs successfully
